apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-web'
  labels:
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/version: '{{ .Chart.Version }}'
    app.kubernetes.io/component: web
spec:
  selector:
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: web
  ports:
    - protocol: TCP
      name: "web"
      port: 80
      targetPort: web