apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ .Release.Name }}-fleets'
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
