apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-deploy-server-fleets
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
