appVersion: "1.0.0"
hostname: "example.com"
web:
  replicaCount: 1
  repository:
    image: ijmacd/docker-deploy-server
  tls:
    enabled: false
  auth:
    enabled: true
    type: basic
    secretName: basic-auth
    realm: 'Authentication Required'
    # Creating secret for basic auth:
    #   htpasswd -c auth foo
    #   kubectl create secret generic basic-auth --from-file=auth
  local:
    enabled: false
  resources:
    requests:
      cpu: 5m
      memory: 100Mi
    limits:
      memory: 100Mi
